[package]
name = "zala"
version = "0.1.0"
authors = ["Colin Davidson <colin@pentaquine.com>"]

[dependencies]
glium = "*"
glium_text = "*"
image = "*"
time = "*"
zpu = { git = "https://github.com/anchovieshat/ZPU.git" }
